
name: PHPUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: your_root_password
          MYSQL_DATABASE: your_database_name
        ports:
          - 3306:3306
        options: --health-check-interval=10s --health-check-timeout=5s --health-check-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Или ваша версия PHP
          extensions: xdebug, pdo, mysql
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --no-ansi --no-progress --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests & Generate Coverage Report
        run: ./vendor/bin/phpunit --coverage-clover clover.xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Установите секрет CODECOV_TOKEN в настройках вашего репозитория GitHub
          flags: unittests
          fail_ci_if_error: true
```